services:
  - type: static
    name: franchise-service-app
    env: static
    branch: main
    buildCommand: npm install && npm run build
    publishPath: dist
    rootDir: .
    envVars:
      - key: VITE_SUPABASE_URL
        value: "https://etympxjjebjfjtfgsvkq.supabase.co"
      - key: VITE_SUPABASE_ANON_KEY
        value: "sb_publishable_fMU2AnAEn8JufkahJ9Cq0w_0qt8MILs"
      - key: VITE_DEV_PASSWORD
        value: ""
